### ISSUE TITLE
how do you pick out coco_40k?

### ISSUE THREAD

**Issue by siyuzou** [microsoft/MeshTransformer#30]
Hi!

I found that a subset of MSCOCO 2017 dataset is used instead of the original dataset. Why you choose these 40k samples? What do you go by when pick them out? Have you tried using the full MSCOCO dataset to train and is there any difference?

I guess it's to guarantee at least several valid keypoints, but I wish a confirm.

Look forward to your reply!

**Comment by kevinlin311tw** [comment]
Great question! We filter the samples by the number of visible keypoints. If the sample have >=12 visible keypoints, we include the sample in our training, resulting in a total of ~40k samples. This is the same as GraphCMR. We follow their procedure.

We actually tried to use full MSCOCO, but we observed performance degradation. It is about ~3 PA-MPJPE worse. We think this is mainly because in our 2D-reprojection, we don't have penalty on the invisible keypoints. If the majority of the human body is out-of-the-view, it is free to hallucinate... and difficult to optimize 2D re-projection at least in our framework. 

You may find out-of-the-view examples in the supplementary material of our Mesh Graphormer paper.

**Comment by siyuzou** [comment]
Thanks for your quick and detailed reply! :)
