### ISSUE TITLE
bounding boxes

### ISSUE THREAD

**Issue by mahsaep** [microsoft/MeshTransformer#54]
Hi and thanks for releasing the code!

From the visualizations that I generated during training an inference, I realised that the box that is used to cropped the image to obtain a person which is given as input to the model at train and test time is not tight around that person and sometimes include other people in the image as well. Could you please let me know the reason?
Thanks!

**Comment by kevinlin311tw** [comment]
During our GT preparation, we did bbox expansion by a factor of 1.2 (you could check relevant code [here](https://github.com/microsoft/MeshTransformer/blob/main/metro/tools/tsv_demo_up3d.py#L81)). So that for inference, the bboxes should be slightly larger than the original GT bbox. Sometimes you may see a larger bbox that include other people.
This scaling process is adopted from GraphCMR (CVPR 2019) implementation.

Further, during the training, we perform training data augmentation which will randomly scale the bbox a bit larger/smaller. Thus, the bbox may not be tight around the person.

**Comment by kevinlin311tw** [comment]
Please re-open this thread if you encounter relevant issues or bugs. Thank you.
