### ISSUE TITLE
Interpreting the training outputs

### ISSUE THREAD

**Issue by bozo-wd** [microsoft/MeshTransformer#9]
Hi, 

thanks for the amazing work. 

I have a question regarding some initial output results (as the training seems to be taking, the next, 40 days on my single GTX 3090 card). 

As one can see in the image bellow there are 2d keypoints in the left column, as well as the estimated SMPL in the right one.

There are examples of fitting in the places where it, I assume intentionally, occluded. Is it a potential issue? 
![visual_4_108000](https://user-images.githubusercontent.com/81355992/121210523-09274300-c87c-11eb-958c-22ca631a18cf.jpg)

Also in another example, there is a weird SMPL estimation, and there are plenty of those, in some batches it estimates without these spikes.
![visual_12_300000](https://user-images.githubusercontent.com/81355992/121211325-ada98500-c87c-11eb-8dcd-875d6734dac2.jpg)

Any feedback on those are highly appreciated.

Cheers!

**Comment by kevinlin311tw** [comment]
Thanks for the questions!

We usually use (partially-) occluded training samples to improve model training. In many datasets, their 2D keypoint annotations have the visibility flags. If a specific keypoint is invisible (i.e., occluded), we will simply ignore it. However, in the examples you mentioned above, I see there is one extreme case that the entire human body is occluded. We may need to remove these kind of training samples in future. I believe the training sample is from MuCo-3DHP dataset.

I also observed the spike issue. I usually see the spikes when it is in an early training stage. This is probably because the image-mesh alignment is still not good. Could you please let me know the number of iterations/epoches you tried to obtain these examples?

**Comment by bozo-wd** [comment]
Wow, that was an instant feedback. Cheers for that.

Regarding the extreme case that the entire body is occluded. The reason why I have asked is that it actually works good, considering that it sees nothing. also the score is scarily high. 

Finally, regarding the spikes, you are right, it is the early training stage, I was checking it just because it happens that in some evaluations it actually works fine, then in the following one, the spikes appear again, but I assume it also depends from random evaluation images.

For example after 238000 iterations:
![visual_9_238000](https://user-images.githubusercontent.com/81355992/121361144-4d2a4e80-c935-11eb-95fc-ee3367cc0422.jpg)

After 28600 iterations:
![visual_12_286000](https://user-images.githubusercontent.com/81355992/121362278-4819cf00-c936-11eb-8cb1-94f8102b33e4.jpg)

and it goes back and forth.

But your feedback, that it is because image-mesh alignment is not good, makes absolute sense. As is too early to make other assumption.

Have a good one,
Cheers
